-- MySQL Script generated by MySQL Workbench
-- Wed Dec 11 21:00:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kart` ;

-- -----------------------------------------------------
-- Schema kart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kart` DEFAULT CHARACTER SET utf8 ;
USE `kart` ;

-- -----------------------------------------------------
-- Table `kart`.`piloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kart`.`piloto` ;

CREATE TABLE IF NOT EXISTS `kart`.`piloto` (
  `id_piloto` INT NOT NULL AUTO_INCREMENT,
  `nome_piloto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_piloto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kart`.`Corrida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kart`.`Corrida` ;

CREATE TABLE IF NOT EXISTS `kart`.`Corrida` (
  `Id_corrida` INT NOT NULL AUTO_INCREMENT,
  `hora_corr` VARCHAR(20) NOT NULL,
  `volta_corr` VARCHAR(2) NOT NULL,
  `tempo_corr` VARCHAR(20) NOT NULL,
  `velocidade_corr` FLOAT NOT NULL,
  `piloto_id_piloto` INT NOT NULL,
  PRIMARY KEY (`Id_corrida`, `piloto_id_piloto`))
ENGINE = InnoDB;

CREATE INDEX `fk_Corrida_piloto_idx` ON `kart`.`Corrida` (`piloto_id_piloto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
